//! Related-scope analysis, obligations, reviews, typed messages, replay and waits (#21).
//! Analyzer checks use the real pinned rust-analyzer/Cargo and gopls/Go toolchains.
use falinks::*;
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::Command,
    time::Duration,
};
use tempfile::TempDir;

const RUST: &[(&str, &str)] = &[
    (
        "Cargo.toml",
        "[package]\nname = \"probe\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    ),
    (
        "Cargo.lock",
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"probe\"\nversion = \"0.1.0\"\n",
    ),
    (
        "src/lib.rs",
        "mod dep;\n\npub fn left() -> i32 {\n    1\n}\n\npub fn right() -> i32 {\n    dep::callee()\n}\n",
    ),
    ("src/dep.rs", "pub fn callee() -> i32 {\n    7\n}\n"),
];
const GO: &[(&str, &str)] = &[
    ("go.mod", "module example.com/probe\n\ngo 1.22\n"),
    (
        "siblings.go",
        "package probe\n\nfunc Left() int {\n\treturn 1\n}\n\nfunc Right() int {\n\treturn Callee()\n}\n",
    ),
    (
        "callee.go",
        "package probe\n\nfunc Callee() int {\n\treturn 7\n}\n",
    ),
];

fn pin(path: PathBuf) -> Pin {
    assert!(path.is_file(), "missing pinned tool {}", path.display());
    Pin {
        sha256: sha256_file(&path).unwrap(),
        path,
    }
}
fn rust_toolchain() -> Toolchain {
    let bin = Path::new(env!("CARGO")).parent().unwrap();
    Toolchain {
        language: Language::Rust,
        executables: ["rust-analyzer", "cargo", "rustc"]
            .iter()
            .map(|t| pin(bin.join(t)))
            .collect(),
        features: Vec::new(),
    }
}
fn go_toolchain() -> Toolchain {
    let env = |key: &str| {
        let out = Command::new("go").args(["env", key]).output().unwrap();
        PathBuf::from(String::from_utf8(out.stdout).unwrap().trim())
    };
    let gopls = std::env::var_os("FALINKS_GOPLS")
        .map(PathBuf::from)
        .unwrap_or_else(|| env("GOPATH").join("bin/gopls"));
    Toolchain {
        language: Language::Go,
        executables: vec![pin(gopls), pin(env("GOROOT").join("bin/go"))],
        features: Vec::new(),
    }
}
fn fixture(files: &[(&str, &str)]) -> (TempDir, Engine, Client, Client) {
    let dir = tempfile::tempdir().unwrap();
    let live = dir.path().join("live");
    for (path, bytes) in files {
        fs::create_dir_all(live.join(path).parent().unwrap()).unwrap();
        fs::write(live.join(path), bytes).unwrap();
    }
    let enrolled: Vec<_> = files.iter().map(|(p, _)| *p).collect();
    let engine = Engine::open(&live, &dir.path().join("state"), &enrolled).unwrap();
    let alice = engine.authenticate(0, &engine.credentials()[0]).unwrap();
    let bob = engine.authenticate(1, &engine.credentials()[1]).unwrap();
    (dir, engine, alice, bob)
}
fn edit(id: &str, capture: &Capture, path: &str, bytes: &str) -> Request {
    Request {
        id: id.into(),
        expected: BTreeMap::from([(path.into(), capture.files[path].version)]),
        output: BTreeMap::from([(
            path.into(),
            Some(File {
                bytes: bytes.as_bytes().to_vec(),
                executable: false,
            }),
        )]),
    }
}
fn text(capture: &Capture, path: &str) -> String {
    String::from_utf8(capture.files[path].file.as_ref().unwrap().bytes.clone()).unwrap()
}

#[test]
fn rust_and_go_evidence_identify_owners_and_compiler_relationships() {
    for (files, toolchain, right, callee) in [
        (
            RUST,
            rust_toolchain(),
            "src/lib.rs#right",
            "src/dep.rs#callee",
        ),
        (GO, go_toolchain(), "siblings.go#Right", "callee.go#Callee"),
    ] {
        let (_dir, engine, _, _) = fixture(files);
        let evidence = engine.configure_analysis(vec![toolchain.clone()]).unwrap();
        let evidence = &evidence[0];
        assert!(evidence.errors.is_empty(), "{:?}", evidence.errors);
        assert!(evidence.unknown.is_empty(), "{:?}", evidence.unknown);
        assert_eq!(evidence.tree, engine.capture().unwrap().tree);
        assert_eq!(evidence.tools.len(), toolchain.executables.len());
        assert!(evidence.tools.iter().all(|t| !t.version.is_empty()));
        let owners: Vec<_> = evidence.owners.values().flatten().map(|o| &o.id).collect();
        assert!(owners.iter().any(|o| *o == right), "{owners:?}");
        assert!(owners.iter().any(|o| *o == callee), "{owners:?}");
        assert!(
            evidence
                .edges
                .contains(&(right.to_string(), callee.to_string())),
            "{:?}",
            evidence.edges
        );
    }
}

fn scope(id: &str, nodes: &[&str]) -> Scope {
    Scope {
        id: id.into(),
        task: format!("task {id}"),
        nodes: nodes.iter().map(|n| n.to_string()).collect(),
    }
}
fn reread(engine: &Engine, client: &Client, scope: &str) -> Obligation {
    let capture = engine.capture().unwrap();
    engine
        .review(
            client,
            Review {
                scope: scope.into(),
                revision: capture.revision,
                decision: Decision::Keep,
                note: "reread current owners".into(),
            },
        )
        .unwrap()
}
fn pending(engine: &Engine, client: &Client) -> Vec<String> {
    engine
        .obligations(client)
        .unwrap()
        .into_iter()
        .filter(Obligation::pending)
        .map(|o| o.scope.id)
        .collect()
}

#[test]
fn rust_relationships_notify_related_scopes_and_let_unrelated_work_proceed() {
    let (_dir, engine, alice, bob) = fixture(RUST);
    engine.configure_analysis(vec![rust_toolchain()]).unwrap();
    engine
        .register(&alice, scope("right", &["src/lib.rs#right"]))
        .unwrap();
    // A sibling owner is model-proven unrelated: no obligation.
    let base = engine.capture().unwrap();
    let left = text(&base, "src/lib.rs").replace("    1\n", "    // grown\n    2\n");
    assert!(matches!(
        engine
            .apply(&bob, edit("left", &base, "src/lib.rs", &left))
            .unwrap(),
        Outcome::Applied { .. }
    ));
    assert!(pending(&engine, &alice).is_empty());
    // Evidence is bound to exact bytes: a shifted owner gets fresh ranges, never old ones.
    let span = |capture: &Capture| {
        let evidence = engine.evidence(capture).unwrap().remove(0);
        assert_eq!(evidence.tree, capture.tree);
        let owner = evidence.owners["src/lib.rs"]
            .iter()
            .find(|o| o.id == "src/lib.rs#right");
        owner.map(|o| o.start).unwrap()
    };
    let grown = "    // grown\n".len();
    assert_eq!(span(&base) + grown, span(&engine.capture().unwrap()));
    // The callee `right` uses is related: a durable obligation.
    let current = engine.capture().unwrap();
    let callee = "pub fn callee() -> i32 {\n    8\n}\n";
    engine
        .apply(&bob, edit("callee", &current, "src/dep.rs", callee))
        .unwrap();
    assert_eq!(pending(&engine, &alice), ["right"]);
    // Related writes are gated; unrelated owners in the same file still progress.
    let current = engine.capture().unwrap();
    let related = text(&current, "src/lib.rs").replace("dep::callee()", "dep::callee() + 1");
    assert!(matches!(
        engine
            .apply(&alice, edit("related", &current, "src/lib.rs", &related))
            .unwrap(),
        Outcome::Unreviewed { .. }
    ));
    let unrelated = text(&current, "src/lib.rs").replace("    2\n", "    3\n");
    assert!(matches!(
        engine
            .apply(
                &alice,
                edit("unrelated", &current, "src/lib.rs", &unrelated)
            )
            .unwrap(),
        Outcome::Applied { .. }
    ));
    assert_eq!(pending(&engine, &alice), ["right"]);
    // Distinct symbols never weaken file freshness.
    let stale = text(&current, "src/lib.rs").replace("    2\n", "    4\n");
    assert!(matches!(
        engine
            .apply(&bob, edit("stale-left", &current, "src/lib.rs", &stale))
            .unwrap(),
        Outcome::Stale { .. }
    ));
    // An earlier review cannot cover a later change, even one restoring old bytes.
    let reviewed_before = engine.capture().unwrap();
    let restore = "pub fn callee() -> i32 {\n    7\n}\n";
    engine
        .apply(
            &bob,
            edit("restore", &reviewed_before, "src/dep.rs", restore),
        )
        .unwrap();
    let partial = engine
        .review(
            &alice,
            Review {
                scope: "right".into(),
                revision: reviewed_before.revision,
                decision: Decision::Revise,
                note: "reviewed the older revision".into(),
            },
        )
        .unwrap();
    assert!(partial.pending());
    assert!(!reread(&engine, &alice, "right").pending());
    let current = engine.capture().unwrap();
    let related = text(&current, "src/lib.rs").replace("dep::callee()", "dep::callee() + 1");
    assert!(matches!(
        engine
            .apply(
                &alice,
                edit("related-after-review", &current, "src/lib.rs", &related)
            )
            .unwrap(),
        Outcome::Applied { .. }
    ));
    let live_edits: Vec<_> = engine
        .events(&bob, 0)
        .unwrap()
        .into_iter()
        .filter_map(|e| match e.body {
            Body::Message(m) if m.kind == Kind::LiveEdit => Some(m),
            _ => None,
        })
        .collect();
    let last = live_edits.last().unwrap();
    assert_eq!(last.sender, 0);
    assert_eq!(last.work, Work::Revision(current.revision + 1));
    assert_eq!(last.scope, ["src/lib.rs#right"]);
}

#[test]
fn broken_go_evidence_and_configuration_changes_widen_symmetrically() {
    let (_dir, engine, alice, bob) = fixture(GO);
    engine.configure_analysis(vec![go_toolchain()]).unwrap();
    engine
        .register(&alice, scope("left", &["siblings.go#Left"]))
        .unwrap();
    let callee =
        |body: &str| format!("package probe\n\nfunc Callee() int {{\n\treturn {body}\n}}\n");
    let base = engine.capture().unwrap();
    engine
        .apply(&bob, edit("healthy", &base, "callee.go", &callee("8")))
        .unwrap();
    assert!(
        pending(&engine, &alice).is_empty(),
        "Callee is unrelated to Left"
    );
    let current = engine.capture().unwrap();
    engine
        .apply(
            &bob,
            edit("broken", &current, "callee.go", &callee("Undefined()")),
        )
        .unwrap();
    let evidence = engine.evidence(&engine.capture().unwrap()).unwrap();
    assert!(evidence[0].units.values().any(|u| !u.broken.is_empty()));
    assert_eq!(pending(&engine, &alice), ["left"], "broken package widens");
    reread(&engine, &alice, "left");
    let current = engine.capture().unwrap();
    engine
        .apply(
            &bob,
            edit(
                "config",
                &current,
                "go.mod",
                "module example.com/probe\n\ngo 1.23\n",
            ),
        )
        .unwrap();
    assert_eq!(
        pending(&engine, &alice),
        ["left"],
        "configuration widens to everything"
    );
}

#[test]
fn interface_implementations_relate_without_any_reference_edge() {
    let (_dir, engine, alice, bob) = fixture(&[
        ("go.mod", "module example.com/probe\n\ngo 1.22\n"),
        (
            "shape.go",
            "package probe\n\ntype Shape interface {\n\tArea() int\n}\n",
        ),
        (
            "square.go",
            "package probe\n\ntype Square struct{}\n\nfunc (Square) Area() int {\n\treturn 1\n}\n",
        ),
    ]);
    engine.configure_analysis(vec![go_toolchain()]).unwrap();
    engine
        .register(&alice, scope("shape", &["shape.go#Shape"]))
        .unwrap();
    let base = engine.capture().unwrap();
    let square = text(&base, "square.go").replace("return 1", "return 2");
    engine
        .apply(&bob, edit("area", &base, "square.go", &square))
        .unwrap();
    assert_eq!(pending(&engine, &alice), ["shape"]);
}

#[test]
fn changed_pins_and_unknown_input_universes_fail_closed() {
    let (_dir, engine, alice, bob) = fixture(RUST);
    let mut wrong = rust_toolchain();
    wrong.executables[0].sha256 = "0".repeat(64);
    assert!(engine.configure_analysis(vec![wrong]).is_err());
    // Without verified evidence every change is related.
    engine
        .register(&alice, scope("right", &["src/lib.rs#right"]))
        .unwrap();
    let base = engine.capture().unwrap();
    let left = text(&base, "src/lib.rs").replace("    1\n", "    2\n");
    engine
        .apply(&bob, edit("left", &base, "src/lib.rs", &left))
        .unwrap();
    assert_eq!(pending(&engine, &alice), ["right"]);

    let mut files = RUST.to_vec();
    files[0].1 = "[package]\nname = \"probe\"\nversion = \"0.1.0\"\nedition = \"2024\"\nbuild = \"build.rs\"\n";
    files.push(("build.rs", "fn main() {}\n"));
    let (_dir, engine, alice, _) = fixture(&files);
    let evidence = engine.configure_analysis(vec![rust_toolchain()]).unwrap();
    assert!(!evidence[0].unknown.is_empty());
    let base = engine.capture().unwrap();
    let left = text(&base, "src/lib.rs").replace("    1\n", "    2\n");
    assert!(matches!(
        engine.apply(&alice, edit("blocked", &base, "src/lib.rs", &left)).unwrap(),
        Outcome::Rejected { reason } if reason.contains("recapture")
    ));
    assert_eq!(engine.capture().unwrap(), base);
}

fn plain() -> (TempDir, Engine, Client, Client) {
    fixture(&[("a.rs", "fn a() {}\n"), ("b.rs", "fn b() {}\n")])
}

#[test]
fn deferred_relevant_edit_blocks_stale_and_unreviewed_writes_until_reassessment() {
    let (_dir, engine, alice, bob) = plain();
    engine.register(&alice, scope("a", &["a.rs"])).unwrap();
    let base = engine.capture().unwrap();
    engine
        .apply(&bob, edit("peer", &base, "b.rs", "fn b() { a(); }\n"))
        .unwrap();
    let events = engine.events(&alice, 0).unwrap();
    assert_eq!(events.len(), 2, "{events:?}");
    for event in &events {
        engine
            .handle(
                &alice,
                event.seq,
                Disposition::Deferred {
                    note: "finish reasoning".into(),
                },
            )
            .unwrap();
    }
    // Deferral and receipt are not reassessment.
    assert_eq!(pending(&engine, &alice), ["a"]);
    // Alice's write relies on b.rs as she last read it.
    let mut stale = edit("stale", &base, "a.rs", "fn a() { old }\n");
    stale
        .expected
        .insert("b.rs".into(), base.files["b.rs"].version);
    assert!(matches!(
        engine.apply(&alice, stale).unwrap(),
        Outcome::Stale { .. }
    ));
    let current = engine.capture().unwrap();
    assert!(matches!(
        engine
            .apply(
                &alice,
                edit("unreviewed", &current, "a.rs", "fn a() { new }\n")
            )
            .unwrap(),
        Outcome::Unreviewed { .. }
    ));
    for event in &events {
        engine
            .handle(&alice, event.seq, Disposition::Processed)
            .unwrap();
    }
    assert_eq!(pending(&engine, &alice), ["a"]);
    reread(&engine, &alice, "a");
    assert!(matches!(
        engine
            .apply(
                &alice,
                edit("reviewed", &current, "a.rs", "fn a() { new }\n")
            )
            .unwrap(),
        Outcome::Applied { .. }
    ));
    assert!(engine.request(&alice, "unreviewed").unwrap().is_some());
}

#[test]
fn replay_restores_deferred_context_and_obligations_without_duplicates_after_restart() {
    let (dir, engine, alice, bob) = plain();
    engine.register(&alice, scope("a", &["a.rs"])).unwrap();
    let base = engine.capture().unwrap();
    engine
        .apply(&bob, edit("peer", &base, "b.rs", "changed\n"))
        .unwrap();
    let events = engine.events(&alice, 0).unwrap();
    assert!(
        engine
            .handle(&alice, events[1].seq, Disposition::Processed)
            .is_err(),
        "no skipping"
    );
    engine
        .handle(
            &alice,
            events[0].seq,
            Disposition::Deferred {
                note: "later".into(),
            },
        )
        .unwrap();
    drop(engine);
    let engine = Engine::open(
        &dir.path().join("live"),
        &dir.path().join("state"),
        &["a.rs", "b.rs"],
    )
    .unwrap();
    let alice = engine.authenticate(0, &engine.credentials()[0]).unwrap();
    let restored = engine.pending(&alice).unwrap();
    assert_eq!(restored.handled, events[0].seq);
    assert_eq!(restored.deferred.len(), 1);
    assert_eq!(restored.deferred[0].0, events[0], "stable identity");
    assert_eq!(restored.unhandled, events[1..]);
    assert_eq!(restored.obligations.len(), 1);
    // Redelivery after a crash before the cursor save is duplicate-safe.
    for _ in 0..2 {
        engine
            .handle(
                &alice,
                events[0].seq,
                Disposition::Deferred {
                    note: "again".into(),
                },
            )
            .unwrap();
        engine
            .handle(&alice, events[1].seq, Disposition::Processed)
            .unwrap();
    }
    let again = engine.pending(&alice).unwrap();
    assert_eq!(again.deferred.len(), 1);
    assert_eq!(again.deferred[0].1, "later");
    assert!(again.unhandled.is_empty());
    assert_eq!(again.obligations.len(), 1);
    assert_eq!(engine.events(&alice, 0).unwrap(), events);
}

#[test]
fn waits_catch_up_on_missed_wakeups_and_report_explicit_outcomes() {
    let (_dir, engine, alice, bob) = plain();
    let plan = |text: &str| Plan {
        task: "consumer".into(),
        scope: vec!["b.rs".into()],
        work: Work::None,
        text: text.into(),
        reply_to: None,
    };
    // Committed before the wait began: catch-up, not a lost wakeup.
    let early = engine.post(&bob, plan("early")).unwrap();
    assert!(
        engine
            .wait(&bob, Condition::Message { from: 1, after: 0 }, None, None)
            .is_err()
    );
    let from_bob = |after| Condition::Message { from: 1, after };
    assert_eq!(
        engine
            .wait(&alice, from_bob(0), Some(Duration::ZERO), None)
            .unwrap(),
        WaitOutcome::Met(early.clone())
    );
    std::thread::scope(|scope| {
        let waiter = scope.spawn(|| engine.wait(&alice, from_bob(early.seq), None, None));
        std::thread::sleep(Duration::from_millis(50));
        engine.post(&bob, plan("late")).unwrap();
        assert!(matches!(
            waiter.join().unwrap().unwrap(),
            WaitOutcome::Met(_)
        ));
    });
    let after = engine.events(&alice, 0).unwrap().last().unwrap().seq;
    assert_eq!(
        engine
            .wait(
                &alice,
                from_bob(after),
                Some(Duration::from_millis(20)),
                None
            )
            .unwrap(),
        WaitOutcome::TimedOut
    );
    let cancel = engine.cancel_token();
    std::thread::scope(|scope| {
        let waiter = scope.spawn(|| engine.wait(&alice, from_bob(after), None, Some(&cancel)));
        std::thread::sleep(Duration::from_millis(50));
        cancel.cancel();
        assert_eq!(waiter.join().unwrap().unwrap(), WaitOutcome::Cancelled);
    });
    std::thread::scope(|scope| {
        let waiter = scope.spawn(|| engine.wait(&alice, from_bob(after), None, None));
        std::thread::sleep(Duration::from_millis(50));
        engine.disconnect(&bob).unwrap();
        assert_eq!(
            waiter.join().unwrap().unwrap(),
            WaitOutcome::Disconnected { agent: 1 }
        );
    });
    // Retry after reconnection is explicit and works normally.
    let bob = engine.authenticate(1, &engine.credentials()[1]).unwrap();
    engine.post(&bob, plan("back")).unwrap();
    assert!(matches!(
        engine.wait(&alice, from_bob(after), None, None).unwrap(),
        WaitOutcome::Met(_)
    ));
}

#[test]
fn checkpoint_offers_survive_live_editing_and_end_exact_waits_without_rebinding() {
    let (_dir, engine, alice, bob) = plain();
    engine.register(&bob, scope("b", &["b.rs"])).unwrap();
    let base = engine.capture().unwrap();
    let offer = |id: &str, revision: u64, supersedes: Option<&str>| Offer {
        id: id.into(),
        task: "producer".into(),
        revision,
        scope: vec!["b.rs".into()],
        text: format!("offer {id}"),
        supersedes: supersedes.map(String::from),
    };
    let c1 = engine
        .offer(&bob, offer("c1", base.revision, None))
        .unwrap();
    engine
        .apply(&bob, edit("draft", &base, "b.rs", "later live draft\n"))
        .unwrap();
    assert_eq!(
        engine.checkpoint(&c1.id).unwrap().unwrap(),
        c1,
        "live edits leave the offer intact"
    );
    // A reply binds the original message and its exact work.
    let offered = engine
        .events(&alice, 0)
        .unwrap()
        .into_iter()
        .find(|e| matches!(&e.body, Body::Message(m) if m.kind == Kind::CheckpointOffer))
        .unwrap();
    let reply = |work: Work| Plan {
        task: "consumer".into(),
        scope: vec!["a.rs".into()],
        work: work.clone(),
        text: "reviewed this checkpoint".into(),
        reply_to: Some(Reply {
            event: offered.seq,
            work,
        }),
    };
    assert!(engine.post(&alice, reply(Work::Revision(1))).is_err());
    engine
        .post(&alice, reply(Work::Checkpoint(c1.id.clone())))
        .unwrap();
    // A peer edit renews Bob's obligation; offers covering it are gated.
    let current = engine.capture().unwrap();
    engine
        .apply(&alice, edit("peer", &current, "a.rs", "fn a() { 2 }\n"))
        .unwrap();
    let current = engine.capture().unwrap();
    assert!(
        engine
            .offer(&bob, offer("c2", current.revision, Some("c1")))
            .is_err()
    );
    assert!(
        engine
            .offer(&bob, offer("older", base.revision, None))
            .is_err(),
        "pending review blocks even an older offer"
    );
    reread(&engine, &bob, "b");
    let wait = Condition::Checkpoint { id: c1.id.clone() };
    std::thread::scope(|scope| {
        let waiter = scope.spawn(|| engine.wait(&alice, wait.clone(), None, None));
        std::thread::sleep(Duration::from_millis(50));
        engine
            .offer(&bob, offer("c2", current.revision, Some("c1")))
            .unwrap();
        assert_eq!(
            waiter.join().unwrap().unwrap(),
            WaitOutcome::Superseded {
                checkpoint: c1.id.clone(),
                replacement: "1/c2".into()
            }
        );
    });
    assert_eq!(
        engine.checkpoint(&c1.id).unwrap().unwrap().capture,
        base,
        "history retained"
    );
    engine.withdraw(&bob, "c2").unwrap();
    assert_eq!(
        engine
            .wait(
                &alice,
                Condition::Checkpoint { id: "1/c2".into() },
                None,
                None
            )
            .unwrap(),
        WaitOutcome::Withdrawn {
            checkpoint: "1/c2".into()
        }
    );
    let c3 = engine
        .offer(&bob, offer("c3", current.revision, None))
        .unwrap();
    engine.disconnect(&bob).unwrap();
    assert_eq!(
        engine
            .wait(&alice, Condition::Checkpoint { id: c3.id }, None, None)
            .unwrap(),
        WaitOutcome::Disconnected { agent: 1 }
    );
}
